### ISSUE TITLE
Section 3 Python Programming on Clusters notes/edits

### ISSUE THREAD

**Issue by samanthacsik** [NCEAS/scalable-computing-course#2]
@jeanetteclark I ran through the setup in [Section 3](https://learning.nceas.ucsb.edu/2022-09-arctic/sections/03-python-intro.html) and added a couple notes where I needed to take a couple extra steps. Ran into an error while trying to install dependencies, but that might just be me...

### 3.3 Starting a project

- Connect to the server - open the command palette (`Cmd` + `Shift` + `P`) and type “Remote SSH: Connect to Host”

**Note:** If “Remote SSH: Connect to Host” is not an option, you may need to first install the [Remote SSH extension](https://code.visualstudio.com/docs/remote/ssh-tutorial)

- Select “Add New SSH Host” then enter the ssh command to connect to the host as if in a terminal (`ssh username@included-crab.nceas.ucsb.edu`)

**Note:** you should only have to do this step once

- Select the SSH config file to update with the name of the host (if prompted)

- Click “Connect” in the popup in the lower right hand corner. Enter your password in the dialog box that pops up

**Note:** If the dialog box does not appear, reopen the command palette (`Cmd` + `Shift` + `P`), type in “Remote-SSH: Connect to Host…“, choose `included-crab.nceas.ucsb.edu` from the options of configured SSH hosts, then enter your password into the dialog box that appears

- Clone your fork of the `scalable-computing-examples` repo

**Note:** Do this in the VS Code terminal using the command `git clone <url-to-forked-repo-here>`

- Open the folder into your workspace - File > Open Folder - Enter password again if prompted

### 3.4 Virtual Environments

Why virtual environments? We’ll answer this.

First we will create `.bash_profile` file to create variables that point to the install locations of python and `virtualenvwrapper`. `.bash_profile` is just a text file that contains bash commands that are run every time you start up a new terminal. Although setting up this file is not required to use `virtualenvwrapper`, it is convenient because it allows you to set up some reasonable defaults to the commands (meaning less typing, overall), and it makes sure that the package is available every time you start a new terminal.

Set up the .bash_profile file.
- Select ‘File > New Text File’
- Paste the following lines into your `.bash_profile` file

`export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3`  
`export VIRTUALENVWRAPPER_VIRTUAWORKON_HOME=$HOME/.virtualenvs`. 
`source /usr/share/virtualenvwrapper/virtualenvwrapper.sh`

The first line points `virtualenvwrapper` to the default python installation to use. In this case, we point it to the system wide install of python on the server. The next line sets the directory where your virtual environments will be stored. We point it to a hidden directory (`.virtualenvs`) in your home directory. Finally, the last line sources a bash script that ships with `virtualenvwrapper`, which makes all of `virtualenvwrapper` commands available in your terminal session. Save the file in the top of your home directory as `.bash_profile`

- Restart your terminal, then check to make sure it was installed and configured correctly  
`mkvirtualenv --version`

You should see something that looks like**(??)**:  
`virtualenv 20.14.1 from /usr/local/lib/python3.6/dist-packages/virtualenv/__init__.py`

- Now we can create the virtual environment we will use for the course. 
`mkvirtualenv scomp`

By default, this will point to our Python 3.9 installation on the server, because of the settings in `.bash_profile`. If you want to point to a different version of python, or be more explicit about the version, you can use the -p flag and pass a path to the python install, like so:  
` mkvirtualenv -p /usr/bin/python3 test`

After making a virtual environment, it will automatically be activated. You’ll see the name of the env you are working in on the left side of your terminal prompt in parentheses. To deactivate your environment (like if you want to work on a different project), just run `deactivate`. To activate it again, run:  
`workon scomp`

You can get a list of all available environments by just running:  
`workon`

Now let’s install the dependencies for this course into that environment. 
`python3 -m pip install -r requirements.txt`

..... got an error after this step
`ERROR: Could not find a version that satisfies the requirement bleach==5.0.0 (from versions: 0.2.1, 0.2.2, 0.3, 0.3.1, 0.3.3, 0.3.4, 0.5.0, 0.5.1, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.2, 1.2.1, 1.2.2, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.5.0, 2.0.0, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 3.0.0, 3.0.1, 3.0.2, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.1.5, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.3.0, 3.3.1, 4.0.0, 4.1.0)
ERROR: No matching distribution found for bleach==5.0.0`

**Comment by jeanetteclark** [comment]
Thanks again for the review @samanthacsik. I incorporated all of these so I'm going to close
